CREATE TABLE MOVIE(
ID NUMBER,
CONSTRAINT ID PRIMARY KEY (ID),
TITLE NVARCHAR2(50) NOT NULL,
DIRECTOR NVARCHAR2(50) NOT NULL,
YEAR NUMBER(4,0),
CONSTRAINT YEAR CHECK(YEAR BETWEEN '1900' AND '2018'),
LENGTH_MINS NUMBER(4) CHECK(LENGTH_MINS BETWEEN 10 AND 200)
);


-- CREATE TABLE movie(
-- id NUMBER,
-- CONSTRAINT id PRIMARY KEY (ID),
-- title NVARCHAR2(50) NOT NULL,
-- director NVARCHAR2(50) NOT NULL,
-- year NUMBER(4),
-- CHECK(year BETWEEN '1900' AND EXTRACT(YEAR FROM DATE (SYSDATE FROM DUAL))),
-- year NUMBER(4) CHECK(year BETWEEN '1900' AND EXTRACT(YEAR FROM NOW())),
-- year NUMBER(4) CHECK(year BETWEEN '1900' AND EXTRACT(YEAR FROM CURRENT_TIMESTAMP)),
-- length_mins NUMBER(4) CHECK(length_mins BETWEEN 10 AND 200)
-- );
--
-- DROP TABLE movie;