-- SELECT -column 1, column 2- FROM table_name
-- WHERE conditions
-- GROUP BY column_name


SELECT AVG(PRICE), PRODUCT_NAME FROM ORDERS
GROUP BY PRODUCT_NAME;

SELECT PRODUCT_NAME, PRICE FROM ORDERS
ORDER BY PRODUCT_NAME ASC;

SELECT SUM(PRICE) FROM ORDERS;

SELECT COUNT(PRICE) FROM ORDERS;

SELECT COUNT(*) FROM ORDERS
WHERE PRICE > 222;


-- SELECT -column 1, column 2- FROM table_name
-- WHERE conditions AND EXISTS (SELECT -column 1, column 2- FROM table_name
-- WHERE conditions)

SELECT * FROM ORDERS
WHERE EXISTS (SELECT * FROM PRODUCT WHERE PRODUCT_NAME = ORDERS.PRODUCT_NAME);

SELECT * FROM ORDERS
WHERE EXISTS (SELECT * FROM PRODUCT WHERE /*can be: SELECT * FROM table .... */ PRODUCT_NAME = ORDERS.PRODUCT_NAME AND cost_PRICE > ORDERS.PRICE);


SELECT * FROM ORDERS
WHERE DATE_ORDERED BETWEEN TO_DATE ('15.11.2018') AND TO_DATE ('15.12.2018');

-- SELECT * FROM table_name WHERE conditions AND/OR column_name LIKE 'pattern';
-- % - as any symbols
SELECT * FROM ORDERS
WHERE PRODUCT_NAME LIKE 's%';
