CREATE TABLE ROOM_ORDERS (
ID NUMBER CHECK(ID < 10001),
CONSTRAINT order_pk PRIMARY KEY(id),
USER_ID NUMBER UNIQUE,
ROOM_ID NUMBER UNIQUE,
DATE_FROM DATE NOT NULL,
DATE_TO DATE NOT NULL,
MONEY_PAID NUMBER(8,2) NOT NULL
);