CREATE TABLE SUPPLIERS (
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIER_PK PRIMARY KEY (SUPPLIER_ID),
COMPANY_NAME NVARCHAR2(128) NOT NULL,
CONTACT_NAME NVARCHAR2(50),
CONTACT_TITLE NVARCHAR2(128),
ADDRESS NVARCHAR2(128),
CITY NVARCHAR2(50),
REGION NVARCHAR2(50),
POSTAL_CODE NUMBER(5,0),
COUNTRY NVARCHAR2(128),
PHONE NUMBER(12,0),
FAX NUMBER(12,0),
HOME_PAGE NVARCHAR2(128)
);

CREATE TABLE CATEGORIES (
CATEGORY_ID NUMBER,
CONSTRAINT CATEGORY_PK PRIMARY KEY (CATEGORY_ID),
CATEGORY_NAME NVARCHAR2(128) NOT NULL,
DESCRIPTION CLOB,
PICTURE NVARCHAR2(128)
);

CREATE TABLE PRODUCTS (
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID),
PRODUCT_NAME NVARCHAR2(128) NOT NULL,
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIER_ID_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS (SUPPLIER_ID),
CATEGORY_ID NUMBER,
CONSTRAINT CATEGORY_ID_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID),
QUANTITY_PER_UNIT NUMBER(9,0),
UNIT_PRICE NUMBER(9,2),
UNITS_IN_STOCK NUMBER(9,0),
UNITS_ON_ORDER NUMBER(9,0),
REORDER_LEVEL NUMBER(4,0),
DISCONTINUED NUMBER(1,0) CHECK (DISCONTINUED = 0 OR DISCONTINUED = 1)
);


CREATE TABLE EMPLOYEES (
EMPLOYEE_ID NUMBER,
CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID),
LAST_NAME NVARCHAR2(50) NOT NULL,
FIRST_NAME NVARCHAR2(50) NOT NULL,
TITLE NVARCHAR2(128),
TITLE_OF_COURTESY NVARCHAR2(128),
BIRTHDATE DATE,
HIRE_DATE DATE,
ADDRESS NVARCHAR2(128),
CITY NVARCHAR2(50),
REGION NVARCHAR2(50),
POSTAL_CODE NUMBER(5,0),
COUNTRY NVARCHAR2(128),
HOME_PHONE NUMBER(12,0),
EXTENSION NUMBER(4,0),
PHOTO NVARCHAR2(128),
NOTES NVARCHAR2(1000),
REPORTS_TO NUMBER,
CONSTRAINT REPORTS_TO_FK FOREIGN KEY (REPORTS_TO) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);


CREATE TABLE CUSTOMERS (
CUSTOMER_ID NUMBER,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
COMPANY_NAME NVARCHAR2(128) NOT NULL,
CONTACT_NAME NVARCHAR2(50),
CONTACT_TITLE NVARCHAR2(128),
ADDRESS NVARCHAR2(128),
CITY NVARCHAR2(50),
REGION NVARCHAR2(50),
POSTAL_CODE NUMBER(5,0),
COUNTRY NVARCHAR2(128),
PHONE NUMBER(12,0),
FAX NUMBER(12,0)
);


CREATE TABLE SHIPPERS (
SHIPPER_ID NUMBER,
CONSTRAINT SHIPPER_PK PRIMARY KEY (SHIPPER_ID),
COMPANY_NAME NVARCHAR2(128) NOT NULL,
PHONE NUMBER(12,0)
);


CREATE TABLE ORDERS (
ORDER_ID NUMBER,
CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID),
CUSTOMER_ID NUMBER,
CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
EMPLOYEE_ID NUMBER,
CONSTRAINT EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
ORDER_DATE TIMESTAMP,
REQUIRED_DATE TIMESTAMP,
SHIPPED_DATE TIMESTAMP,
SHIP_VIA NUMBER,
CONSTRAINT SHIPPER_FK FOREIGN KEY (SHIP_VIA) REFERENCES SHIPPERS (SHIPPER_ID),
FREIGHT NUMBER(9,2),
SHIP_NAME NVARCHAR2(128),
SHIP_ADDRESS NVARCHAR2(128),
SHIP_CITY NVARCHAR2(50),
SHIP_REGION NVARCHAR2(50),
SHIP_POSTAL_CODE NUMBER(5,0),
SHIP_COUNTRY NVARCHAR2(128)
);


CREATE TABLE ORDER_DETAILS (
ORDER_ID NUMBER,
CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID),
UNIT_PRICE_QUANTITY_DISCOUNT NUMBER(4,2)
);