CREATE TABLE DEAL (
CUSTOMER_ID NUMBER,
CONSTRAINT CUSTOMER_ID_D_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
AMOUNT NUMBER(8,0) NOT NULL,
DATE_DEAL TIMESTAMP NOT NULL
);

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, CUSTOMER.CITY
FROM SALESMAN, CUSTOMER
WHERE SALESMAN.CITY = CUSTOMER.CITY;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, CUSTOMER.CITY
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.CITY = CUSTOMER.CITY;

INSERT INTO DEAL VALUES (3002, 10000, TO_DATE('08.08.2017'));
INSERT INTO DEAL VALUES (3002, 1000, TO_DATE('08.09.2017'));
INSERT INTO DEAL VALUES (3005, 5000, TO_DATE('08.08.2018'));
INSERT INTO DEAL VALUES (3001, 10000, TO_DATE('08.08.2017'));
INSERT INTO DEAL VALUES (3003, 10000, TO_DATE('08.08.2018'));
INSERT INTO DEAL VALUES (3005, 1100, TO_DATE('08.08.2018'));
INSERT INTO DEAL VALUES (3001, 15000, TO_DATE('08.09.2017'));


SELECT CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY
FROM CUSTOMER
    JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID
    JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID AND DEAL.AMOUNT > 10000
    GROUP BY CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY;

SELECT CUSTOMER.CUSTNAME
FROM CUSTOMER
    JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
                    AND DEAL.DATE_DEAL BETWEEN TO_DATE ('01.01.2017') AND TO_DATE ('31.12.2018')
GROUP BY CUSTOMER.CUSTNAME;


SELECT CUSTOMER.CUSTNAME
FROM (SELECT CUSTOMER.CUSTNAME, SUM(DEAL.AMOUNT)
FROM CUSTOMER
    JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
                    AND DEAL.DATE_DEAL BETWEEN TO_DATE ('01.08.2017') AND TO_DATE ('31.08.2017')
GROUP BY CUSTOMER.CUSTNAME);


SELECT MAX(SALESMAN.COMMISSION) FROM SALESMAN;



--variant 1
SELECT NAME
FROM (
SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT) SUMS
        FROM CUSTOMER
             JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
                      AND DEAL.DATE_DEAL BETWEEN TO_DATE ('01.08.2017') AND TO_DATE ('31.08.2017')
             JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID
            GROUP BY SALESMAN.NAME)
   WHERE SUMS = (SELECT MAX(SUMS)
   FROM
   (SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT) SUMS
        FROM CUSTOMER
             JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
                      AND DEAL.DATE_DEAL BETWEEN TO_DATE ('01.08.2017') AND TO_DATE ('31.08.2017')
             JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID
            GROUP BY SALESMAN.NAME));



--variant 2 0.33c
CREATE VIEW SALESMAN_SUMS AS SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT) SUMS
        FROM CUSTOMER
             JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
                      AND DEAL.DATE_DEAL BETWEEN TO_DATE ('01.08.2017') AND TO_DATE ('31.08.2017')
             JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID
            GROUP BY SALESMAN.NAME;
SELECT NAME
FROM SALESMAN_SUMS
WHERE SUMS = (SELECT MAX(SUMS) FROM SALESMAN_SUMS);


--variant 3 0.19c
SELECT NAME, SUMS
  FROM (SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT) SUMS,
               RANK() OVER (ORDER BY SUM(DEAL.AMOUNT) DESC) RANKE_SUMS
        FROM CUSTOMER
             JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
                  AND DEAL.DATE_DEAL BETWEEN TO_DATE ('01.08.2017') AND TO_DATE ('31.08.2017')
             JOIN SALESMAN ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
        GROUP BY SALESMAN.NAME)
 WHERE RANKE_SUMS = 1;


--variant 4 0.11c
SELECT NAME FROM (SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT) SUMS
        FROM CUSTOMER
             JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
                      AND DEAL.DATE_DEAL BETWEEN TO_DATE ('01.08.2017') AND TO_DATE ('31.08.2017')
             JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID
            GROUP BY SALESMAN.NAME)
   WHERE SUMS = (SELECT MAX(MAKS)
                    FROM (SELECT SUM(DEAL.AMOUNT) MAKS FROM DEAL
                                WHERE DEAL.DATE_DEAL BETWEEN TO_DATE ('01.08.2017') AND TO_DATE ('31.08.2017')
                                GROUP BY DEAL.CUSTOMER_ID));

--variant 5 0.128c
WITH
    SALESMAN_SUMS AS (SELECT SALESMAN.NAME NAME, SUM(DEAL.AMOUNT) SUMS
        FROM CUSTOMER
             JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
                      AND DEAL.DATE_DEAL BETWEEN TO_DATE ('01.08.2017') AND TO_DATE ('31.08.2017')
             JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID
            GROUP BY SALESMAN.NAME)
SELECT NAME FROM SALESMAN_SUMS
WHERE SUMS = (SELECT MAX(SALESMAN_SUMS.SUMS) FROM SALESMAN_SUMS);