CREATE TABLE FORUM_CATEGORIES (
ID NUMBER,
CONSTRAINT CATEGORY_PK PRIMARY KEY (ID),
TITLE NVARCHAR2(64),
DISCRIPTION CLOB,
DATE_CATEGORY TIMESTAMP,
IP NVARCHAR2(20)
);

CREATE TABLE FORUM_SUBCATEGORIES (
ID NUMBER,
CONSTRAINT SUBCATEGORY_PK PRIMARY KEY (ID),
ID_CATEGORY NUMBER,
CONSTRAINT CATEGORY_FK FOREIGN KEY (ID_CATEGORY) REFERENCES FORUM_CATEGORIES (ID),
TITLE NVARCHAR2(45),
DISCRIPTION CLOB,
DATE_SUBCATEGORY TIMESTAMP,
IP NVARCHAR2(20)
);

CREATE TABLE USERS (
ID NUMBER,
CONSTRAINT USER_PK PRIMARY KEY (ID),
NICK NVARCHAR2(16),
PASSWORD NVARCHAR2(128),
EMAIL NVARCHAR2(128),
DATE_USER TIMESTAMP,
KARMA NUMBER(9,2),
IP NVARCHAR2(20)
);

CREATE TABLE FORUM_POSTS (
ID NUMBER,
CONSTRAINT POST_PK PRIMARY KEY (ID),
ID_SUBCATEGORY NUMBER,
CONSTRAINT SUBCATEGORY_FK FOREIGN KEY (ID_SUBCATEGORY) REFERENCES FORUM_SUBCATEGORIES (ID),
ID_USER NUMBER,
CONSTRAINT USER_FK FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
PARENT_POST NUMBER,
CONSTRAINT PARENT_POST_FK FOREIGN KEY (PARENT_POST) REFERENCES FORUM_POSTS (ID),
TITLE NVARCHAR2(90),
POST_CONTENT CLOB,
IS_POLL NUMBER(1,0) CHECK (IS_POLL = 0 OR IS_POLL = 1),
POST_DATE TIMESTAMP,
IP NVARCHAR2(20)
);

CREATE TABLE FORUM_POLLS_OPTIONS (
ID NUMBER,
CONSTRAINT POLL_PK PRIMARY KEY (ID),
ID_POST NUMBER,
CONSTRAINT POST_FK FOREIGN KEY (ID_POST) REFERENCES FORUM_POSTS (ID),
TITLE NVARCHAR2(64),
POLL_DATE TIMESTAMP
);


CREATE TABLE FORUM_POLLS_OPTIONS_VOTES (
ID NUMBER,
CONSTRAINT POLL_VOTES_PK PRIMARY KEY (ID),
ID_POLL NUMBER,
CONSTRAINT POLL_VOTE_FK FOREIGN KEY (ID_POLL) REFERENCES FORUM_POLLS_OPTIONS (ID),
ID_USER NUMBER,
CONSTRAINT USER_PV_FK FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
DATE_POLL_VOTE TIMESTAMP,
IP NVARCHAR2(20)
);